src/TenderWinMini.Web.Portal/Models/BriefTenderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TenderWinMini.Web.Portal.Models {
    public class BriefTenderViewModel {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Decimal Prise { get; set; }
        public int DaysLeft { get; set; }
    }
}

src/TenderWinMini.Web.Portal/Models/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TenderWinMini.Web.Portal.Models {
    public class DocumentViewModel {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

src/TenderWinMini.Web.Portal/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TenderWinMini.Web.Portal.Models {
    public class EventViewModel {
        public string Text { get; set; }
        public DateTime EvetnDate { get; set; }
    }
}

src/TenderWinMini.Web.Portal/Models/TenderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TenderWinMini.Data.Contracts.Models.Entities;

namespace TenderWinMini.Web.Portal.Models {
    public class TenderViewModel {
        public string Name { get; set; }
        public Decimal Prise { get; set; }
        public DateTime PublicatedDate { get; set; }
        public DateTime CompletedDate { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryAddress { get; set; }
    }
}

src/TenderWinMini.Web.Portal/Controllers/Base/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TenderWinMini.Web.Portal.Controllers.Base
{
    public class BaseController : Controller
    {
    }
}

src/TenderWinMini.Web.Portal/Controllers/TenderController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TenderWinMini.Logic.Contracts.Services;
using TenderWinMini.Web.Portal.Controllers.Base;
using TenderWinMini.Web.Portal.Models;

namespace TenderWinMini.Web.Portal.Controllers {
    public class TenderController : BaseController {
        private readonly ITenderService _tenderService;
        public TenderController(ITenderService tenderService) {
            _tenderService = tenderService;
        }

        public async Task<ActionResult> GetTenderList(int page = 1, string search = "", decimal? priceFrom = null, decimal? priceTo = null,
            DateTime? publicationFrom = null, DateTime? publicationTo = null) {
            var model = Mapper.Map<IEnumerable<BriefTenderViewModel>>(await _tenderService.GetTenderList(page, search, priceFrom, priceTo, publicationFrom, publicationTo));

            if (Request.IsAjaxRequest()) {
                return PartialView("_Items", model);
            }
            return View(model);
        }

        public async Task<ActionResult> GetTenderById(Guid id) {
            var model = Mapper.Map<TenderViewModel>(await _tenderService.GetTenderById(id));

            return PartialView(model);
        }

        public async Task<ActionResult> GetDocumentListByTenderId(Guid id) {
            var model = Mapper.Map<IEnumerable<DocumentViewModel>>(await _tenderService.GetDocumentListByTenderId(id));

            return PartialView(model);
        }

        public async Task<ActionResult> GetEventListByTenderId(Guid id) {
            var model = Mapper.Map<IEnumerable<EventViewModel>>(await _tenderService.GetEventListByTenderId(id));

            return PartialView(model);
        }
    }
}

src/TenderWinMini.Web.Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/TenderWinMini.Web.Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/TenderWinMini.Web.Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/TenderWinMini.Web.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/TenderWinMini.Web.Portal/Views/Tender/GetDocumentListByTenderId.cshtml
@model IEnumerable<TenderWinMini.Web.Portal.Models.DocumentViewModel>

<ul class="list-group">
    @foreach (var b in Model) {
        <li class="list-group-item"><a href="@b.Url">Document: @b.Name</a></li>
    }
</ul>

src/TenderWinMini.Web.Portal/Views/Tender/GetEventListByTenderId.cshtml
@model IEnumerable<TenderWinMini.Web.Portal.Models.EventViewModel>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Text</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var b in Model) {
            <tr>
                <td>@b.Text</td>
                <td>@b.EvetnDate</td>
            </tr>
        }
    </tbody>
</table>

src/TenderWinMini.Web.Portal/Views/Tender/GetTenderById.cshtml
@model TenderWinMini.Web.Portal.Models.TenderViewModel

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Name</h3>
    </div>
    <div class="panel-body">
        <p>Price: @Model.Prise</p>
        <p>Publicated date: @Model.PublicatedDate</p>
        <p>Completed date: @Model.CompletedDate</p>
        <p>Delivery time: @Model.DeliveryTime</p>
        <p>Delivery address: @Model.DeliveryAddress</p>
    </div>
</div>

src/TenderWinMini.Web.Portal/Views/Tender/GetTenderList.cshtml
@model IEnumerable<TenderWinMini.Web.Portal.Models.BriefTenderViewModel>

@{
    ViewBag.Title = "GetTenderList";
}

<div style="width: 50%; padding: 10px; background: lightblue; position: fixed; margin: 10px; left: 45%" id="tenderInfo">
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1" id="tab1">Tender Info</a></li>
            <li><a href="#tabs-2" id="tab2">Documents</a></li>
            <li><a href="#tabs-3" id="tab3">Events</a></li>
        </ul>
        <div id="tabs-1">
        </div>
        <div id="tabs-2">
        </div>
        <div id="tabs-3">
        </div>
    </div>
</div>

<img src='@Url.Content("~/Content/search.png")' id="find" data-toggle="modal" data-target="#myModal">

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Enter the search parameters</h4>
            </div>
            @using (Html.BeginForm("GetTenderList", "Tender", FormMethod.Get)) {
                <div class="modal-body">
                    <div class="form-group">
                        <label>Input name:</label>
                        <input type="text" class="form-control" id="search" name="search" placeholder="Input name">
                    </div>
                    <div class="form-group">
                        <label>Input price:</label>
                        <input type="text" class="form-control" id="priceFrom" name="priceFrom" placeholder="from">
                        <input type="text" class="form-control" id="priceTo" name="priceTo" placeholder="to">
                    </div>
                    <div class="form-group">
                        <label>Date publication:</label>
                        <input type="text" class="form-control" id="publicationFrom" name="publicationFrom" placeholder="from">
                        <input type="text" class="form-control" id="publicationTo" name="publicationTo" placeholder="to">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Ok</button>
                </div>
            }
        </div>
    </div>
</div>

<div style="width: 45%; padding: 10px" id="scrolList">
    @Html.Partial("_Items")
</div>

<div id="loading"><img src='@Url.Content("~/Content/loading_spinner.gif")'></div>

@section Scripts
{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            $('div#loading').hide();
            selectItems();
            $('#publicationFrom').datepicker();
            $('#publicationTo').datepicker();
            $("#tabs").tabs();
            $('#tenderInfo').append('<div style="position: absolute;top:0;left:0;width: 100%;height:100%;z-index:2;opacity:0.4;filter: alpha(opacity = 50);background:grey" id="blockDiv"></div>');

            var page = 1;
            var _inCallback = false;

            function loadItems() {
                if (page > -1 && !_inCallback) {
                    _inCallback = true;
                    page++;
                    $('div#loading').show();
                    $.ajax({
                        type: 'GET',
                        url: '/Tender/GetTenderList?page=' + page,
                        success: function (data, textstatus) {
                            if (data != '') {
                                $("#scrolList").append(data);
                                selectItems();
                            }
                            else {
                                page = -1;
                            }
                            _inCallback = false;
                            $("div#loading").hide();
                        }
                    });
                }
            }

            $(window).scroll(function () {
                if ($(window).scrollTop() == $(document).height() - $(window).height()) {

                    loadItems();
                }
            });

            var selectedTempId = null;

            function selectItems() {
                $('.card').on("click", function () {
                    $("#" + selectedTempId).removeClass("selected");
                    $("#" + this.id).addClass("selected");
                    selectedTempId = this.id;
                    $("#blockDiv").remove();

                    $.ajax({
                        type: 'GET',
                        url: '/Tender/GetTenderById/' + this.id,
                        success: function (data, textstatus) {
                            if (data != '') {
                                $("#tabs-1").empty().append(data);
                                $("#tabs").tabs("option", "active", 0);
                            }
                        }
                    });
                });
            }

            $('#tab2').on("click", function () {
                console.log(selectedTempId);
                $.ajax({
                    type: 'GET',
                    url: '/Tender/GetDocumentListByTenderId/' + selectedTempId,
                    success: function (data, textstatus) {
                        if (data != '') {
                            $("#tabs-2").empty().append(data);
                        }
                    }
                });
            });

            $('#tab3').on("click", function () {
                console.log(selectedTempId);
                $.ajax({
                    type: 'GET',
                    url: '/Tender/GetEventListByTenderId/' + selectedTempId,
                    success: function (data, textstatus) {
                        if (data != '') {
                            $("#tabs-3").empty().append(data);
                        }
                    }
                });
            });
        })
    </script>
}

src/TenderWinMini.Web.Portal/Views/Tender/_Items.cshtml
@model IEnumerable<TenderWinMini.Web.Portal.Models.BriefTenderViewModel>

@foreach (var b in Model) {
    <div class="card" id="@b.Id">
        <div class="container">
            <h4><b>Tender: @b.Name</b></h4>
            <p>Price: @b.Prise</p>
            <p>Days Left: @b.DaysLeft</p>
        </div>
    </div>
}